[profile.default]
solc = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
bytecode_hash = 'none'

[fmt] # See https://book.getfoundry.sh/reference/config/formatter
single_line_statement_block = "preserve"
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "single"

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
hoodi = "${HOODI_RPC_URL}"
chiado = "${CHIADO_RPC_URL}"
gnosis = "${GNOSIS_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
hoodi = { key = "${ETHERSCAN_API_KEY}", chain = 560048, url = "https://api-hoodi.etherscan.io/api" }
chiado = { key = "${GNOSISSCAN_API_KEY}" }
gnosis = { key = "${GNOSISSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
