[profile.default]
solc = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
bytecode_hash = 'none'
remappings = [
    # v3-core uses its own OpenZeppelin
    "lib/v3-core:@openzeppelin/contracts-upgradeable/=lib/v3-core/lib/openzeppelin-contracts-upgradeable/contracts/",
    "lib/v3-core:@openzeppelin/contracts/=lib/v3-core/lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    # Root project OpenZeppelin
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@stakewise-core/=lib/v3-core/contracts/",
    "@stakewise-test/=lib/v3-core/test/",
    "@aave-core/=lib/aave-v3-origin/src/contracts/",
    "safe/=lib/composable-cow/lib/safe/contracts/",
    "@composable-cow/=lib/composable-cow/src/",
    "@cowprotocol/=lib/composable-cow/lib/cowprotocol/src/",
]

[lint]
lint_on_build = false

[fmt] # See https://book.getfoundry.sh/reference/config/formatter
single_line_statement_block = "preserve"
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "single"

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
hoodi = "${HOODI_RPC_URL}"
chiado = "${CHIADO_RPC_URL}"
gnosis = "${GNOSIS_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
hoodi = { key = "${ETHERSCAN_API_KEY}", chain = 560048, url = "https://api-hoodi.etherscan.io/api" }
chiado = { key = "${GNOSISSCAN_API_KEY}" }
gnosis = { key = "${GNOSISSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
